name: Fossology
on:
  workflow_dispatch: {}

jobs:
  license_check_job: 
    name: license_check
    runs-on: ubuntu-18.04
    container: ghcr.io/project332/flutter_test_app/flutter:1
    steps: 
     - name:  Checkout
       uses: actions/checkout@v2
       
     # FOSSOLOGY
     - name: fossology report 
       run:   docker run --rm -v /home/runner/work/flutter_testing_app/flutter_testing_app:/project fossology/atarashi:latest -a DLD  /project/
      
   
       
