name: Fossology
on:
  workflow_dispatch: {}

jobs:
  license_check_job: 
    name: license_check
    runs-on: ubuntu-18.04
    container: ghcr.io/project332/flutter_test_app/flutter:1
    steps: 
     - name:  Checkout
       uses: actions/checkout@v1
     # Install Flutter command
     - uses: subosito/flutter-action@v1
       with:
            channel: 'dev'

     # Build Website
     - name: Build Website
       run: |
            flutter config --enable-web
            flutter build web
     # docker instalation
     - name: docker configuration
       run: | 
         apt-get update
         apt-get install  ca-certificates curl gnupg lsb-release
         mkdir -p /etc/apt/keyrings
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
         echo \
         "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
         apt-get update
         apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
         docker --version
     # FOSSOLOGY
     - name: fossology report 
       run:   docker run --rm -v /home/runner/work/flutter_testing_app/flutter_testing_app:/project fossology/atarashi:latest -a DLD  /project/
      
   
       
